### ISSUE TITLE
SEE seems to have an issue

### ISSUE THREAD

**Issue by DRuffer** [sdwood68/YAFFA#2]
> > see emit

Word is a primitive OK

> > see key

Code Field Address: 321
Addr    XT      Name
$141    25963
$143    29817
$145    0       ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ
ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ
$147    0       ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ

**Comment by sdwood68** [comment]
DRuffer, 
Did you try and redefine the word key? I just tested it on my working version and it responded with the following

YAFFA - Yet Another Forth For Arduino, Version 0.6
 Copyright (C) 2012 Stuart Wood
 This program comes with ABSOLUTELY NO WARRANTY.
 This is free software, and you are welcome to
 redistribute it under certain conditions.

 Terminal Echo is On
 Pre-Defined Words : 157
 Input Buffer: Starts at $6AB, Ends at $70A
 Token Buffer: Starts at $68B, Ends at $6AA
 Forth Space: Starts at $140, Ends at $63F
 313 ($139) bytes free

> > see key

Word is a primitive OK

> > see emit

Word is a primitive OK


Please Email directly since I've not been in the habit of checking github.

Thanks

Stuart

**Comment by sdwood68** [comment]
I've verified this issue. It seems to be sensitive to the order in witch you type the the commands. 
    see key 
    see emit 
this works but if the order is reversed
    see emit
    see key
you get bogus information as if it is trying to interpret some other segment of memory instead of recognizing key as a primitive.
